### ISSUE TITLE
can it be made working in msys64 as well? seems to work in windows cmd only.

### ISSUE THREAD

**Issue by emabee** [Detegr/rust-ctrlc#10]

**Comment by Detegr** [comment]
I'm not aware how to support msys64 at the moment, but I don't think it would not be possible. I'll look into this as soon as I have time.

**Comment by henninglive** [comment]
The problem is how minty [interacts with programs that use a native Windows API for command-line user interaction](https://github.com/mintty/mintty/wiki/Tips#inputoutput-interaction-with-alien-programs). A workaround is to use [winpty ](https://github.com/rprichard/winpty)which wraps your program and translates the interface into something that minty can understand.

**Comment by henninglive** [comment]
I notice something funny, minty/msys2 ignores `CTRL+BREAK` while we treat `CTRL+BREAK` the same as `CTRL+C`. This means `CTRL+BREAK` works as expected under minty/msys2 even though `CTRL+C` is broken.

**Comment by Sgeo** [comment]
Is this related to it not working in Cygwin, or is that a separate issue?

**Comment by Detegr** [comment]
Tested with MSYS2 on Windows 10. Works as expected.

**Comment by michaelboyles** [comment]
It doesn't work for me, on Windows 11, with this MSYS2 version

```
MINGW64_NT-10.0-22631 version 3.4.10-87d57229.x86_64 (@fv-az844-235) (gcc version 13.2.0 (GCC) ) 2024-02-14 20:17 UTC
```

Might be related to https://github.com/msys2/msys2-runtime/issues/176
