### ISSUE TITLE
Cleaning up spawned threads.

### ISSUE THREAD

**Issue by glennpierce** [Detegr/rust-ctrlc#29]
I has a service that in addition to processing some data also sets up a web frontend with iron in a thread.

ie

```
scope.spawn(move || {
            web::serve();
});
```

I intercept ctrl-c like to stop my data processing like so

ctrlc::set_handler(move || {
       stop_data_processing();
}).expect("Error setting Ctrl-C handler");

However, this leaves the web server process still running. Without the handler all processes are cleaned up at exit. What do I need to do to clean up all spawn threads ?

Thanks

**Comment by henninglive** [comment]
I am not sure I understand what the problem is, but the only safe way to cleanup threads is to manually stop/join them. In this case, you would stop the webserver by [telling iron to stop listening for connections](https://docs.rs/iron/0.5.1/iron/struct.Listening.html#method.close). Calling [std::process::exit](https://doc.rust-lang.org/std/process/fn.exit.html) and relying on the OS for cleanup might also be an option, but this might be unsafe depending on your situation.

**Comment by glennpierce** [comment]
I guess I was mostly curious how rust can kill all the processes / threads when I don't have a ctrl-c handler but when I do they get left behind ?

**Comment by glennpierce** [comment]
Think I got it going. It wasn't the iron thread but needing to call std::process::exit  as you said.

**Comment by henninglive** [comment]
For future reference. The default action on `CTRL+C` is to terminate the process. This is semantically equivalent to calling [`std::process::exit()`](https://doc.rust-lang.org/std/process/fn.exit.html). When you register a handler, the default behaviour is overridden and the handler is executed instead. Therefore, if you want to want to terminate after running your cleanup code, you need to manually call [`std::process::exit()`](https://doc.rust-lang.org/std/process/fn.exit.html) at end of your handler. One thing to keep in mind is that no destructors are executed when you terminate a process in this way.
